# permissions for end users to view birds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bird-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bird-controller
    app.kubernetes.io/part-of: bird-controller
    app.kubernetes.io/managed-by: kustomize
  name: bird-viewer-role
rules:
- apiGroups:
  - bird.my.domain
  resources:
  - birds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bird.my.domain
  resources:
  - birds/status
  verbs:
  - get
